CREATE TABLE `block` (
     `hash` varchar(128) NOT NULL DEFAULT '' COMMENT '区块hash',
     `number` bigint(20) NOT NULL COMMENT '区块高度',
     `parent_hash` varchar(128) NOT NULL COMMENT '父区块hash',
     `nonce` varchar(128) NOT NULL COMMENT 'Nonce值',
     `miner` varchar(64) NOT NULL COMMENT '出块节点地址',
     `extra_data` mediumtext COMMENT '附加数据',
     `size` int(11) NOT NULL COMMENT '区块大小',
     `energon_used` varchar(255) NOT NULL COMMENT '能量消耗',
     `energon_limit` varchar(255) NOT NULL COMMENT '能量限制',
     `energon_average` varchar(255) NOT NULL COMMENT '平均能量消耗',
     `transaction_number` int(11) NOT NULL DEFAULT '0' COMMENT '区块包含交易个数',
     `timestamp` timestamp NOT NULL COMMENT '出块时间（单位：秒）',
     `block_reward` varchar(64) NOT NULL COMMENT '区块奖励，单位：wei',
     `chain_id` varchar(64) NOT NULL DEFAULT '' COMMENT '链id',
     `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
     `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
     `actual_tx_cost_sum` varchar(255) NOT NULL DEFAULT '0' COMMENT '区块中交易实际花费值(手续费)总和，单位：wei',
     `block_vote_amount` bigint(20) DEFAULT '0' COMMENT '区块内投票交易个数',
     `block_vote_number` bigint(20) DEFAULT '0' COMMENT '区块中包含的选票张数',
     `block_campaign_amount` bigint(20) DEFAULT '0' COMMENT '区块内竞选交易个数',
     `node_name` varchar(32) DEFAULT NULL COMMENT '节点名称',
     `node_id` varchar(255) DEFAULT NULL COMMENT '节点ID',
     `vote_hash` varchar(255) DEFAULT NULL COMMENT '该区块所属节点在当前轮选中的见证票所在交易',
     `reward_ratio` double DEFAULT NULL COMMENT '该区块所属节点在当前轮选中的分红比例:小数',
     `vote_price` varchar(255) DEFAULT NULL COMMENT '票价',
     PRIMARY KEY (`hash`,`number`,`chain_id`)
) ;
