CREATE TABLE `transaction` (
   `hash` varchar(128) NOT NULL DEFAULT '' COMMENT '交易hash',
   `block_number` bigint(20) NOT NULL COMMENT '区块高度',
   `block_hash` varchar(128) NOT NULL COMMENT '区块hash',
   `from` varchar(64) NOT NULL COMMENT '交易发起方地址',
   `to` varchar(64) NOT NULL COMMENT '交易接收方地址',
   `input` text NOT NULL COMMENT '交易输入数据',
   `timestamp` timestamp NOT NULL COMMENT '交易时间（单位：秒）',
   `energon_used` varchar(255) NOT NULL COMMENT '能量消耗',
   `energon_limit` varchar(255) NOT NULL COMMENT '能量限制',
   `energon_price` varchar(255) NOT NULL COMMENT '能量限制',
   `value` varchar(255) NOT NULL COMMENT '交易金额',
   `nonce` varchar(128) NOT NULL COMMENT 'Nonce值',
   `transaction_index` int(11) NOT NULL COMMENT '交易在区块中位置',
   `tx_receipt_status` int(11) NOT NULL COMMENT '交易状态 \r\n1 成功 \r\n0 失败',
   `actual_tx_cost` varchar(255) NOT NULL DEFAULT '0' COMMENT '交易实际花费值(手续费)，单位：wei',
   `tx_type` varchar(32) NOT NULL COMMENT '交易类型 transfer ：转账 MPCtransaction ： MPC交易 contractCreate ： 合约创建 voteTicket ： 投票-使用col1-col5存储投票参数信息，参数含义与tx_info的json字段顺序一致 transactionExecute ： 合约执行 authorization ： 权限 candidateDeposit：竞选质押 candidateApplyWithdraw：减持质押 candidateWithdraw：提取质押 unknown：未知',
   `fail_reason` text COMMENT '交易输入数据',
   `chain_id` varchar(64) NOT NULL DEFAULT '' COMMENT '链id',
   `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
   `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   `receive_type` varchar(32) NOT NULL COMMENT '交易接收者类型（to是合约还是账户）contract合约、 account账户',
   `tx_info` text NOT NULL COMMENT '交易信息',
   `sequence` bigint(20) NOT NULL COMMENT '区块number + 交易所在区块index',
   `col1` varchar(255) DEFAULT NULL,
   `col2` varchar(255) DEFAULT NULL,
   `col3` varchar(255) DEFAULT NULL,
   `col4` varchar(255) DEFAULT NULL,
   `col5` varchar(255) DEFAULT NULL,
   PRIMARY KEY (`hash`)
);
