package com.platon.browser.dao.mapper;

import com.platon.browser.dao.entity.BlockMissing;
import com.platon.browser.dao.entity.BlockMissingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlockMissingMapper {
    long countByExample(BlockMissingExample example);

    int deleteByExample(BlockMissingExample example);

    int deleteByPrimaryKey(Long number);

    int insert(BlockMissing record);

    int insertSelective(BlockMissing record);

    List<BlockMissing> selectByExample(BlockMissingExample example);

    BlockMissing selectByPrimaryKey(Long number);

    int updateByExampleSelective(@Param("record") BlockMissing record, @Param("example") BlockMissingExample example);

    int updateByExample(@Param("record") BlockMissing record, @Param("example") BlockMissingExample example);

    int updateByPrimaryKeySelective(BlockMissing record);

    int updateByPrimaryKey(BlockMissing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_missing
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<BlockMissing> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_missing
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<BlockMissing> list, @Param("selective") BlockMissing.Column ... selective);
}