package com.platon.browser.dao.mapper;

import com.platon.browser.dao.entity.NodeRanking;
import com.platon.browser.dao.entity.NodeRankingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NodeRankingMapper {
    long countByExample(NodeRankingExample example);

    int deleteByExample(NodeRankingExample example);

    int deleteByPrimaryKey(Long id);

    int insert(NodeRanking record);

    int insertSelective(NodeRanking record);

    List<NodeRanking> selectByExample(NodeRankingExample example);

    NodeRanking selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") NodeRanking record, @Param("example") NodeRankingExample example);

    int updateByExample(@Param("record") NodeRanking record, @Param("example") NodeRankingExample example);

    int updateByPrimaryKeySelective(NodeRanking record);

    int updateByPrimaryKey(NodeRanking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_ranking
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<NodeRanking> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_ranking
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<NodeRanking> list, @Param("selective") NodeRanking.Column ... selective);
}