package com.platon.browser.dao.mapper;

import com.platon.browser.dao.entity.Erc20TokenTransferRecord;
import com.platon.browser.dao.entity.Erc20TokenTransferRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Erc20TokenTransferRecordMapper {
    long countByExample(Erc20TokenTransferRecordExample example);

    int deleteByExample(Erc20TokenTransferRecordExample example);

    int deleteByPrimaryKey(Long id);

    int insert(Erc20TokenTransferRecord record);

    int insertSelective(Erc20TokenTransferRecord record);

    List<Erc20TokenTransferRecord> selectByExample(Erc20TokenTransferRecordExample example);

    Erc20TokenTransferRecord selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") Erc20TokenTransferRecord record, @Param("example") Erc20TokenTransferRecordExample example);

    int updateByExample(@Param("record") Erc20TokenTransferRecord record, @Param("example") Erc20TokenTransferRecordExample example);

    int updateByPrimaryKeySelective(Erc20TokenTransferRecord record);

    int updateByPrimaryKey(Erc20TokenTransferRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erc20_token_transfer_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Erc20TokenTransferRecord> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erc20_token_transfer_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Erc20TokenTransferRecord> list, @Param("selective") Erc20TokenTransferRecord.Column ... selective);
}