package com.platon.browser.dao.mapper;

import com.platon.browser.dao.entity.Erc20TokenDetail;
import com.platon.browser.dao.entity.Erc20TokenDetailExample;
import com.platon.browser.dao.entity.Erc20TokenDetailWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Erc20TokenDetailMapper {
    long countByExample(Erc20TokenDetailExample example);

    int deleteByExample(Erc20TokenDetailExample example);

    int deleteByPrimaryKey(Long id);

    int insert(Erc20TokenDetailWithBLOBs record);

    int insertSelective(Erc20TokenDetailWithBLOBs record);

    List<Erc20TokenDetailWithBLOBs> selectByExampleWithBLOBs(Erc20TokenDetailExample example);

    List<Erc20TokenDetail> selectByExample(Erc20TokenDetailExample example);

    Erc20TokenDetailWithBLOBs selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") Erc20TokenDetailWithBLOBs record, @Param("example") Erc20TokenDetailExample example);

    int updateByExampleWithBLOBs(@Param("record") Erc20TokenDetailWithBLOBs record, @Param("example") Erc20TokenDetailExample example);

    int updateByExample(@Param("record") Erc20TokenDetail record, @Param("example") Erc20TokenDetailExample example);

    int updateByPrimaryKeySelective(Erc20TokenDetailWithBLOBs record);

    int updateByPrimaryKeyWithBLOBs(Erc20TokenDetailWithBLOBs record);

    int updateByPrimaryKey(Erc20TokenDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erc20_token_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Erc20TokenDetailWithBLOBs> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erc20_token_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Erc20TokenDetailWithBLOBs> list, @Param("selective") Erc20TokenDetailWithBLOBs.Column ... selective);
}