package com.platon.browser.dao.mapper;

import com.platon.browser.dao.entity.NOptBak;
import com.platon.browser.dao.entity.NOptBakExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NOptBakMapper {
    long countByExample(NOptBakExample example);

    int deleteByExample(NOptBakExample example);

    int deleteByPrimaryKey(Long id);

    int insert(NOptBak record);

    int insertSelective(NOptBak record);

    List<NOptBak> selectByExample(NOptBakExample example);

    NOptBak selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") NOptBak record, @Param("example") NOptBakExample example);

    int updateByExample(@Param("record") NOptBak record, @Param("example") NOptBakExample example);

    int updateByPrimaryKeySelective(NOptBak record);

    int updateByPrimaryKey(NOptBak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table n_opt_bak
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<NOptBak> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table n_opt_bak
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<NOptBak> list, @Param("selective") NOptBak.Column ... selective);
}