package com.platon.browser.dao.mapper;

import com.platon.browser.dao.entity.PendingTx;
import com.platon.browser.dao.entity.PendingTxExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface PendingTxMapper {
    long countByExample(PendingTxExample example);

    int deleteByExample(PendingTxExample example);

    int deleteByPrimaryKey(String hash);

    int insert(PendingTx record);

    int insertSelective(PendingTx record);

    List<PendingTx> selectByExampleWithBLOBs(PendingTxExample example);

    List<PendingTx> selectByExample(PendingTxExample example);

    PendingTx selectByPrimaryKey(String hash);

    int updateByExampleSelective(@Param("record") PendingTx record, @Param("example") PendingTxExample example);

    int updateByExampleWithBLOBs(@Param("record") PendingTx record, @Param("example") PendingTxExample example);

    int updateByExample(@Param("record") PendingTx record, @Param("example") PendingTxExample example);

    int updateByPrimaryKeySelective(PendingTx record);

    int updateByPrimaryKeyWithBLOBs(PendingTx record);

    int updateByPrimaryKey(PendingTx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pending_tx
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<PendingTx> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pending_tx
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<PendingTx> list, @Param("selective") PendingTx.Column... selective);
}