package com.platon.browser.dao.mapper;

import com.platon.browser.dao.entity.VoteTx;
import com.platon.browser.dao.entity.VoteTxExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface VoteTxMapper {
    long countByExample(VoteTxExample example);

    int deleteByExample(VoteTxExample example);

    int deleteByPrimaryKey(Long id);

    int insert(VoteTx record);

    int insertSelective(VoteTx record);

    List<VoteTx> selectByExample(VoteTxExample example);

    VoteTx selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") VoteTx record, @Param("example") VoteTxExample example);

    int updateByExample(@Param("record") VoteTx record, @Param("example") VoteTxExample example);

    int updateByPrimaryKeySelective(VoteTx record);

    int updateByPrimaryKey(VoteTx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_tx
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<VoteTx> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_tx
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<VoteTx> list, @Param("selective") VoteTx.Column... selective);
}