# ***************************开发配置**************************** #
# 当前激活的配置名称(请不要修改)
profile: hrpatp201018v01500
# 密码加密配置
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
#Spring框架内部配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://192.168.9.191:3306/alaya_browser_${profile}?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: ENC(bpshgjWOgn2d+oGmSTBPNA==)
    password: ENC(bpshgjWOgn2d+oGmSTBPNA==)
  #Redis配置
  redis:
    cluster:
      max-redirects: 3
      nodes: 192.168.9.191:7001,192.168.9.191:7002,192.168.9.191:7003,192.168.9.191:7004,192.168.9.191:7005,192.168.9.191:7006
    password: platscan
  #ES配置
  elasticsearch:
    high-level-client:
      hosts: 192.168.120.103,192.168.120.104,192.168.120.105
      port: 9200
      schema: http
      username: elastic
      password: changeme
      blockIndexName: browser_block_${profile}
      transactionIndexName: browser_transaction_${profile}
      delegationIndexName: browser_delegation_${profile}
      nodeOptIndexName: browser_nodeopt_${profile}
      delegationRewardIndexName: browser_delegation_reward_${profile}
      innerTxIndexName: browser_inner_tx_${profile}
# 内存环形缓冲区大小，必须是2的指数倍
disruptor:
  queue:
    # 区块事件环形缓冲区大小
    block.buffer-size: 1024
    # 采集事件环形缓冲区大小
    collection.buffer-size: 1024
    # 数据补充环形缓冲区大小
    complement.buffer-size: 1024
    # gas price估算消息环形缓冲区大小
    gasestimate.buffer-size: 1024
    # 数据持久化
    persistence:
      #环形缓冲区大小
      buffer-size: 1024
      #每次处理多少个
      batch-size: 10
#日志配置
logging:
  #日志级别
  level:
    org.springframework: error
    org.springframework.retry: error
    com.platon.browser: error
    com.platon.browser.bootstrap: error
    com.platon.browser.collection: error
    com.platon.browser.collection.queue.handler: error
    com.platon.browser.common: error
    com.platon.browser.complement: error
    com.platon.browser.complement.handler: error
    com.platon.browser.complement.converter: error
    com.platon.browser.persistence: error
    com.platon.browser.persistence.handler: error
    com.platon.browser.persistence.queue.handler: error
    com.platon.browser.task: error
  file:
    name: ./logs/${spring.application.name}-${version}-${profile}.log
#PlatOn相关配置
platon:
  # 交易输入参数并行解码线程数
  txLogDecodeThreadNum: 200
  # Web3j访问地址
  web3j:
    #HTTP或WS
    protocol: HTTP
    addresses: 192.168.120.151:6791
  # 质押节点统计年化率最多取多少个连续周期
  maxSettlePeriodCount4AnnualizedRateStat: 4
  #PlatON初始总发行量(ATP)
  initIssueAmount: 100000000
  #每年固定增发比例
  addIssueRate: 0.05
  #每年增发分配给激励池的比例
  incentiveRateFromIssue: 0.4
  #每个共识轮中回退多少个块是选举下一轮验证人的时机
  electionBackwardBlockCount: 20
  #10年内计算士基金会向激励池填充额度: <第几年-补贴金额(ATP)>
  foundationSubsidies: {
    '1':0,
    '2':0,
    '3':0,
    '4':0,
    '5':0,
    '6':0,
    '7':0,
    '8':0,
    '9':0
  }
  # 初始内置节点默认质押金额(ATP)
  defaultStakingLockedAmount: 10500
  #区块最大Gas限制
  maxBlockGasLimit: 100800000
  #提案url参数模板
  proposalUrlTemplate: https://github.com/danielgogo/PIPs/blob/master/PIP-%s.md
  #提案pip_num参数模板
  proposalPipNumTemplate: PIP-%s
  #keysBase网址
  keyBase: https://keybase.io/
  #keyBase api
  keyBaseApi: _/api/1.0/user/lookup.json?key_suffix=
  #链id
  chainId: 201018
  #代币专用Event,格式：{事件名称}:{保存的合约地址索引}#{类型}:{是否indexed},{类型}:{是否indexed}...
  eventDefine: {
    "TokenCreated": "0#address:indexed,string:non-indexed,string:non-indexed,uint8:non-indexed,uint256:non-indexed"
  }
  #Redis命名空间
  redis-namespace: browser:${profile}
  #同步时的索引查询分页参数配置
  paging:
    erc20-transaction:
      pageSize: 2000
      pageCount: 250
# v0.15.0.0版本新增功能涉及的配置
v015:
  #锁仓最小释放金额参数生效版本
  restrictingMinimumReleaseActiveVersion: 3584
  #调账生效版本
  adjustmentActiveVersion: 3840
  #调账提案ID
  adjustmentPipId: '1609410836.4141252'
  #调账日志输出文件
  adjustLogFilePath: /opt/alaya/0.15.0.0/browser-agent/adjust.log

task:
  #地址统计任务
  address-batch-size: 1000
  #动态调整参数
  dynamic-adjust:
    #agent与实际链上区块号相差多少个块号时触发调整操作
    threshold: 20
    #未追上链,批量入ES和Redis的缓存大小
    cache-batch-max-size: 10
    #已追上链,批量入ES和Redis的缓存大小
    cache-batch-min-size: 1