package com.platon.browser.dao.entity;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class Block {
    private Long number;

    private String hash;

    private String parentHash;

    private Date timestamp;

    private Integer size;

    private String gasLimit;

    private String gasUsed;

    private String blockReward;

    private Date createTime;

    private Date updateTime;

    private String nodeName;

    private String nodeId;

    private Integer statTxQty;

    private Integer statTransferQty;

    private Integer statStakingQty;

    private Integer statProposalQty;

    private Integer statDelegateQty;

    private String statTxGasLimit;

    private String statTxFee;

    private String miner;

    private String extraData;

    public Long getNumber() {
        return number;
    }

    public void setNumber(Long number) {
        this.number = number;
    }

    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash == null ? null : hash.trim();
    }

    public String getParentHash() {
        return parentHash;
    }

    public void setParentHash(String parentHash) {
        this.parentHash = parentHash == null ? null : parentHash.trim();
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public Integer getSize() {
        return size;
    }

    public void setSize(Integer size) {
        this.size = size;
    }

    public String getGasLimit() {
        return gasLimit;
    }

    public void setGasLimit(String gasLimit) {
        this.gasLimit = gasLimit == null ? null : gasLimit.trim();
    }

    public String getGasUsed() {
        return gasUsed;
    }

    public void setGasUsed(String gasUsed) {
        this.gasUsed = gasUsed == null ? null : gasUsed.trim();
    }

    public String getBlockReward() {
        return blockReward;
    }

    public void setBlockReward(String blockReward) {
        this.blockReward = blockReward == null ? null : blockReward.trim();
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getNodeName() {
        return nodeName;
    }

    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    public String getNodeId() {
        return nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId == null ? null : nodeId.trim();
    }

    public Integer getStatTxQty() {
        return statTxQty;
    }

    public void setStatTxQty(Integer statTxQty) {
        this.statTxQty = statTxQty;
    }

    public Integer getStatTransferQty() {
        return statTransferQty;
    }

    public void setStatTransferQty(Integer statTransferQty) {
        this.statTransferQty = statTransferQty;
    }

    public Integer getStatStakingQty() {
        return statStakingQty;
    }

    public void setStatStakingQty(Integer statStakingQty) {
        this.statStakingQty = statStakingQty;
    }

    public Integer getStatProposalQty() {
        return statProposalQty;
    }

    public void setStatProposalQty(Integer statProposalQty) {
        this.statProposalQty = statProposalQty;
    }

    public Integer getStatDelegateQty() {
        return statDelegateQty;
    }

    public void setStatDelegateQty(Integer statDelegateQty) {
        this.statDelegateQty = statDelegateQty;
    }

    public String getStatTxGasLimit() {
        return statTxGasLimit;
    }

    public void setStatTxGasLimit(String statTxGasLimit) {
        this.statTxGasLimit = statTxGasLimit == null ? null : statTxGasLimit.trim();
    }

    public String getStatTxFee() {
        return statTxFee;
    }

    public void setStatTxFee(String statTxFee) {
        this.statTxFee = statTxFee == null ? null : statTxFee.trim();
    }

    public String getMiner() {
        return miner;
    }

    public void setMiner(String miner) {
        this.miner = miner == null ? null : miner.trim();
    }

    public String getExtraData() {
        return extraData;
    }

    public void setExtraData(String extraData) {
        this.extraData = extraData == null ? null : extraData.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table block
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        number("number", "number", "BIGINT", true),
        hash("hash", "hash", "VARCHAR", false),
        parentHash("parent_hash", "parentHash", "VARCHAR", false),
        timestamp("timestamp", "timestamp", "TIMESTAMP", true),
        size("size", "size", "INTEGER", true),
        gasLimit("gas_limit", "gasLimit", "VARCHAR", false),
        gasUsed("gas_used", "gasUsed", "VARCHAR", false),
        blockReward("block_reward", "blockReward", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        nodeName("node_name", "nodeName", "VARCHAR", false),
        nodeId("node_id", "nodeId", "VARCHAR", false),
        statTxQty("stat_tx_qty", "statTxQty", "INTEGER", false),
        statTransferQty("stat_transfer_qty", "statTransferQty", "INTEGER", false),
        statStakingQty("stat_staking_qty", "statStakingQty", "INTEGER", false),
        statProposalQty("stat_proposal_qty", "statProposalQty", "INTEGER", false),
        statDelegateQty("stat_delegate_qty", "statDelegateQty", "INTEGER", false),
        statTxGasLimit("stat_tx_gas_limit", "statTxGasLimit", "VARCHAR", false),
        statTxFee("stat_tx_fee", "statTxFee", "VARCHAR", false),
        miner("miner", "miner", "VARCHAR", false),
        extraData("extra_data", "extraData", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table block
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table block
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table block
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table block
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table block
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table block
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table block
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table block
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table block
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table block
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table block
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table block
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table block
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table block
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table block
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}