package com.platon.browser.dao.mapper;

import com.platon.browser.dao.entity.InternalAddress;
import com.platon.browser.dao.entity.InternalAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InternalAddressMapper {
    long countByExample(InternalAddressExample example);

    int deleteByExample(InternalAddressExample example);

    int deleteByPrimaryKey(String address);

    int insert(InternalAddress record);

    int insertSelective(InternalAddress record);

    List<InternalAddress> selectByExample(InternalAddressExample example);

    InternalAddress selectByPrimaryKey(String address);

    int updateByExampleSelective(@Param("record") InternalAddress record, @Param("example") InternalAddressExample example);

    int updateByExample(@Param("record") InternalAddress record, @Param("example") InternalAddressExample example);

    int updateByPrimaryKeySelective(InternalAddress record);

    int updateByPrimaryKey(InternalAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<InternalAddress> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<InternalAddress> list, @Param("selective") InternalAddress.Column ... selective);
}