package com.platon.browser.dao.mapper;

import com.platon.browser.dao.entity.PointLog;
import com.platon.browser.dao.entity.PointLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PointLogMapper {
    long countByExample(PointLogExample example);

    int deleteByExample(PointLogExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(PointLog record);

    int insertSelective(PointLog record);

    List<PointLog> selectByExample(PointLogExample example);

    PointLog selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") PointLog record, @Param("example") PointLogExample example);

    int updateByExample(@Param("record") PointLog record, @Param("example") PointLogExample example);

    int updateByPrimaryKeySelective(PointLog record);

    int updateByPrimaryKey(PointLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<PointLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<PointLog> list, @Param("selective") PointLog.Column ... selective);
}