package com.platon.browser.dao.mapper;

import com.platon.browser.dao.entity.StakingHistory;
import com.platon.browser.dao.entity.StakingHistoryExample;
import com.platon.browser.dao.entity.StakingHistoryKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StakingHistoryMapper {
    long countByExample(StakingHistoryExample example);

    int deleteByExample(StakingHistoryExample example);

    int deleteByPrimaryKey(StakingHistoryKey key);

    int insert(StakingHistory record);

    int insertSelective(StakingHistory record);

    List<StakingHistory> selectByExampleWithBLOBs(StakingHistoryExample example);

    List<StakingHistory> selectByExample(StakingHistoryExample example);

    StakingHistory selectByPrimaryKey(StakingHistoryKey key);

    int updateByExampleSelective(@Param("record") StakingHistory record, @Param("example") StakingHistoryExample example);

    int updateByExampleWithBLOBs(@Param("record") StakingHistory record, @Param("example") StakingHistoryExample example);

    int updateByExample(@Param("record") StakingHistory record, @Param("example") StakingHistoryExample example);

    int updateByPrimaryKeySelective(StakingHistory record);

    int updateByPrimaryKeyWithBLOBs(StakingHistory record);

    int updateByPrimaryKey(StakingHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staking_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<StakingHistory> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staking_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<StakingHistory> list, @Param("selective") StakingHistory.Column ... selective);
}