package com.platon.browser.dao.mapper;

import com.platon.browser.dao.entity.TokenTracker;
import com.platon.browser.dao.entity.TokenTrackerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TokenTrackerMapper {
    long countByExample(TokenTrackerExample example);

    int deleteByExample(TokenTrackerExample example);

    int deleteByPrimaryKey(String address);

    int insert(TokenTracker record);

    int insertSelective(TokenTracker record);

    List<TokenTracker> selectByExample(TokenTrackerExample example);

    TokenTracker selectByPrimaryKey(String address);

    int updateByExampleSelective(@Param("record") TokenTracker record, @Param("example") TokenTrackerExample example);

    int updateByExample(@Param("record") TokenTracker record, @Param("example") TokenTrackerExample example);

    int updateByPrimaryKeySelective(TokenTracker record);

    int updateByPrimaryKey(TokenTracker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_tracker
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<TokenTracker> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_tracker
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<TokenTracker> list, @Param("selective") TokenTracker.Column ... selective);
}