package com.platon.browser.dao.mapper;

import com.github.pagehelper.Page;
import com.platon.browser.dao.entity.TokenInventory;
import com.platon.browser.dao.entity.TokenInventoryExample;
import com.platon.browser.dao.entity.TokenInventoryKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TokenInventoryMapper {
    long countByExample(TokenInventoryExample example);

    int deleteByExample(TokenInventoryExample example);

    int deleteByPrimaryKey(TokenInventoryKey key);

    int insert(TokenInventory record);

    int insertSelective(TokenInventory record);

    Page<TokenInventory> selectByExample(TokenInventoryExample example);

    TokenInventory selectByPrimaryKey(TokenInventoryKey key);

    int updateByExampleSelective(@Param("record") TokenInventory record, @Param("example") TokenInventoryExample example);

    int updateByExample(@Param("record") TokenInventory record, @Param("example") TokenInventoryExample example);

    int updateByPrimaryKeySelective(TokenInventory record);

    int updateByPrimaryKey(TokenInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_inventory
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<TokenInventory> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_inventory
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<TokenInventory> list, @Param("selective") TokenInventory.Column ... selective);
}