package com.platon.browser.dao.mapper;

import com.platon.browser.dao.entity.TxDelegationRewardBak;
import com.platon.browser.dao.entity.TxDelegationRewardBakExample;
import com.platon.browser.dao.entity.TxDelegationRewardBakWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TxDelegationRewardBakMapper {
    long countByExample(TxDelegationRewardBakExample example);

    int deleteByExample(TxDelegationRewardBakExample example);

    int deleteByPrimaryKey(Long id);

    int insert(TxDelegationRewardBakWithBLOBs record);

    int insertSelective(TxDelegationRewardBakWithBLOBs record);

    List<TxDelegationRewardBakWithBLOBs> selectByExampleWithBLOBs(TxDelegationRewardBakExample example);

    List<TxDelegationRewardBak> selectByExample(TxDelegationRewardBakExample example);

    TxDelegationRewardBakWithBLOBs selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") TxDelegationRewardBakWithBLOBs record, @Param("example") TxDelegationRewardBakExample example);

    int updateByExampleWithBLOBs(@Param("record") TxDelegationRewardBakWithBLOBs record, @Param("example") TxDelegationRewardBakExample example);

    int updateByExample(@Param("record") TxDelegationRewardBak record, @Param("example") TxDelegationRewardBakExample example);

    int updateByPrimaryKeySelective(TxDelegationRewardBakWithBLOBs record);

    int updateByPrimaryKeyWithBLOBs(TxDelegationRewardBakWithBLOBs record);

    int updateByPrimaryKey(TxDelegationRewardBak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_delegation_reward_bak
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<TxDelegationRewardBakWithBLOBs> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_delegation_reward_bak
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<TxDelegationRewardBakWithBLOBs> list, @Param("selective") TxDelegationRewardBakWithBLOBs.Column ... selective);
}