package com.platon.browser.dao.mapper;

import com.platon.browser.dao.entity.TxErc1155Bak;
import com.platon.browser.dao.entity.TxErc1155BakExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TxErc1155BakMapper {
    long countByExample(TxErc1155BakExample example);

    int deleteByExample(TxErc1155BakExample example);

    int deleteByPrimaryKey(Long id);

    int insert(TxErc1155Bak record);

    int insertSelective(TxErc1155Bak record);

    List<TxErc1155Bak> selectByExample(TxErc1155BakExample example);

    TxErc1155Bak selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") TxErc1155Bak record, @Param("example") TxErc1155BakExample example);

    int updateByExample(@Param("record") TxErc1155Bak record, @Param("example") TxErc1155BakExample example);

    int updateByPrimaryKeySelective(TxErc1155Bak record);

    int updateByPrimaryKey(TxErc1155Bak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_erc_1155_bak
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<TxErc1155Bak> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_erc_1155_bak
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<TxErc1155Bak> list, @Param("selective") TxErc1155Bak.Column ... selective);
}