package com.platon.browser.dao.mapper;

import com.platon.browser.dao.entity.TxErc20Bak;
import com.platon.browser.dao.entity.TxErc20BakExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TxErc20BakMapper {
    long countByExample(TxErc20BakExample example);

    int deleteByExample(TxErc20BakExample example);

    int deleteByPrimaryKey(Long id);

    int insert(TxErc20Bak record);

    int insertSelective(TxErc20Bak record);

    List<TxErc20Bak> selectByExampleWithBLOBs(TxErc20BakExample example);

    List<TxErc20Bak> selectByExample(TxErc20BakExample example);

    TxErc20Bak selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") TxErc20Bak record, @Param("example") TxErc20BakExample example);

    int updateByExampleWithBLOBs(@Param("record") TxErc20Bak record, @Param("example") TxErc20BakExample example);

    int updateByExample(@Param("record") TxErc20Bak record, @Param("example") TxErc20BakExample example);

    int updateByPrimaryKeySelective(TxErc20Bak record);

    int updateByPrimaryKeyWithBLOBs(TxErc20Bak record);

    int updateByPrimaryKey(TxErc20Bak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_erc_20_bak
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<TxErc20Bak> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_erc_20_bak
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<TxErc20Bak> list, @Param("selective") TxErc20Bak.Column ... selective);
}