package com.platon.browser.dao.mapper;

import com.platon.browser.dao.entity.TxTransferBak;
import com.platon.browser.dao.entity.TxTransferBakExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TxTransferBakMapper {
    long countByExample(TxTransferBakExample example);

    int deleteByExample(TxTransferBakExample example);

    int deleteByPrimaryKey(Long id);

    int insert(TxTransferBak record);

    int insertSelective(TxTransferBak record);

    List<TxTransferBak> selectByExample(TxTransferBakExample example);

    TxTransferBak selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") TxTransferBak record, @Param("example") TxTransferBakExample example);

    int updateByExample(@Param("record") TxTransferBak record, @Param("example") TxTransferBakExample example);

    int updateByPrimaryKeySelective(TxTransferBak record);

    int updateByPrimaryKey(TxTransferBak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_transfer_bak
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<TxTransferBak> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_transfer_bak
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<TxTransferBak> list, @Param("selective") TxTransferBak.Column ... selective);
}